name: Deploy

on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  information:
    if: |
      github.event_name == 'release'
      || (
        github.event_name == 'workflow_run'
        && github.event.workflow_run.conclusion == 'success'
      )
    name: ℹ️ Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.set_outputs.outputs.architectures }}
      build: ${{ steps.information.outputs.build }}
      description: ${{ steps.information.outputs.description }}
      environment: ${{ steps.release.outputs.environment }}
      name: ${{ steps.information.outputs.name }}
      slug: ${{ steps.information.outputs.slug }}
      target: ${{ steps.information.outputs.target }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2

      - name: 🚀 Run add-on information action
        id: information
        uses: frenck/action-addon-information@v1.4.2

      - name: 🛠 Ensure architectures is valid JSON
        id: set_outputs
        run: |
          arch_raw="${{ steps.information.outputs.architectures }}"
          
          if [[ "$arch_raw" != "["* ]]; then
            arch_json=$(echo "$arch_raw" | jq -R 'split(" ")' | jq -c '.')
          else
            arch_json="$arch_raw"
          fi
          
          echo "architectures=$arch_json" >> "$GITHUB_ENV"
          echo "architectures=$arch_json" >> "$GITHUB_OUTPUT"

  deploy:
    name: 👷 Build & Deploy ${{ matrix.architecture }}
    needs: information
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.information.outputs.architectures) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2

      - name: 🏗 Set up QEMU
        uses: docker/setup-qemu-action@v3.4.0

      - name: 🏗 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: 🚀 Build and push
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          tags: |
            ghcr.io/hassio-addons/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}
            ghcr.io/hassio-addons/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}
          context: ${{ needs.information.outputs.target }}
          file: ${{ needs.information.outputs.target }}/Dockerfile
          platforms: linux/${{ matrix.architecture }}
          build-args: |
            BUILD_ARCH=${{ matrix.architecture }}
            BUILD_DESCRIPTION=${{ needs.information.outputs.description }}
            BUILD_NAME=${{ needs.information.outputs.name }}
            BUILD_VERSION=${{ needs.information.outputs.version }}