name: Argon One V3 Fan Control
version: 30a
slug: argon_one_v3_fan_control
description: >
  Advanced fan control for Argon One V3 on Raspberry Pi and Home Assistant Yellow.
  Choose between three modes:
  - **Linear:** Continuous, proportional control between a minimum and maximum temperature.
  - **Fluid:** Non-linear (exponential) scaling with adjustable sensitivity.
  - **Extended:** Discrete multi-level control with extra thresholds and optional quiet profile.
arch:
  - armhf
  - armv7
  - aarch64
auth_api: true
homeassistant_api: true
hassio_role: homeassistant
hassio_api: true
devices:
  - /dev/i2c-*
url: https://community.home-assistant.io/t/argon-one-active-cooling-addon/262598
map:
  - config
  - ssl
  - addons
  - backup
  - share
  - media
options:
  "Fan Control Mode": linear         # Options: linear, fluid, extended
  "Celsius or Fahrenheit": C           # Options: C or F
  "Create a Fan Speed entity in Home Assistant": false
  "Log current temperature every 30 seconds": true
  "Update Interval": 30                # Polling interval in seconds (min=5, max=300)
  # Options for Linear & Fluid modes:
  "Minimum Temperature": 130           # Temperature threshold where fan starts (in chosen unit)
  "Maximum Temperature": 150           # Temperature threshold where fan runs at 100%
  # Fluid Mode only:
  "Fluid Sensitivity": 2.0             # Exponent for non-linear mapping (1.0 = linear; default 2.0)
  # Options for Extended mode:
  "Extended Off Temperature": 130      # Temperature below which the fan remains off
  "Extended Low Temperature": 135      # Threshold for Low level
  "Extended Medium Temperature": 140   # Threshold for Medium level
  "Extended High Temperature": 145     # Threshold for High level
  "Extended Boost Temperature": 150    # Temperature at which fan runs at 100%
  "Quiet Profile": false               # For discrete modes, use reduced fan speeds
schema:
  "Fan Control Mode": list(linear|fluid|extended)
  "Celsius or Fahrenheit": list(C|F)
  "Create a Fan Speed entity in Home Assistant": bool
  "Log current temperature every 30 seconds": bool
  "Update Interval": number(min=5, max=300)
  "Minimum Temperature": number(min=0, max=255)
  "Maximum Temperature": number(min=0, max=255)
  "Fluid Sensitivity": number(min=1, max=5)
  "Extended Off Temperature": number(min=0, max=255)
  "Extended Low Temperature": number(min=0, max=255)
  "Extended Medium Temperature": number(min=0, max=255)
  "Extended High Temperature": number(min=0, max=255)
  "Extended Boost Temperature": number(min=0, max=255)
  "Quiet Profile": bool
