name: ArgonOne V3 Active Multi-Mode Cooling 1.9
version: 31
slug: argon_one_v3_multi
description: Actively keeping your ArgonOne V3 cool with multi-mode control.
arch:
  - armhf
  - armv7
  - aarch64
auth_api: true
homeassistant_api: true
hassio_role: homeassistant
hassio_api: true
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
  - /dev/i2c-21
  - /dev/i2c-22
  - /dev/i2c-23
  - /dev/i2c-24
  - /dev/i2c-25
  - /dev/i2c-26
url: https://community.home-assistant.io/t/argon-one-active-cooling-addon/262598/8
map:
  - config
  - ssl
  - addons
  - backup
  - share
  - media
options:
  ## General Settings
  Temperature Unit: list(C|F)
  Mode: list(Linear|Fluid)
  Update Interval (seconds): int(10,300)
  Log Temperature: bool
  Create a Fan Speed Entity in Home Assistant: bool

  ## Linear Mode Settings
  Minimum Temperature: int(0,255)
  Maximum Temperature: int(0,255)

  ## Fluid Mode Settings
  Low Temperature Threshold: int(0,255)
  Medium Temperature Threshold: int(0,255)
  High Temperature Threshold: int(0,255)
  Quiet Profile (Fluid Mode): bool

  ## Advanced Settings
  I2C Port Override: int(0,26)  # Set to 255 to auto-detect
  Manual Fan Speed Override: int(-1,100)  # -1 disables override; 0-100 forces that percentage
  Fan Ramping Delay (seconds): int(0,10)   # Delay between incremental fan speed changes
  Safety Fan Speed (%): int(0,100)
  Diagnostics Mode: bool
schema:
  Temperature Unit: list(C|F)
  Mode: list(Linear|Fluid)
  Update Interval (seconds): int(10,300)
  Log Temperature: bool
  Create a Fan Speed Entity in Home Assistant: bool
  Minimum Temperature: int(0,255)
  Maximum Temperature: int(0,255)
  Low Temperature Threshold: int(0,255)
  Medium Temperature Threshold: int(0,255)
  High Temperature Threshold: int(0,255)
  Quiet Profile (Fluid Mode): bool
  I2C Port Override: int(0,26)
  Manual Fan Speed Override: int(-1,100)
  Fan Ramping Delay (seconds): int(0,10)
  Safety Fan Speed (%): int(0,100)
  Diagnostics Mode: bool
