version: "31"
slug: argon_one_v3_master_temp
name: ArgonOne V3 Master Cooling
description: "Master fan control for ArgonOne V3 case with enhanced temperature regulation and user-friendly settings."
arch:
  - armhf
  - armv7
  - aarch64
auth_api: true
homeassistant_api: true
hassio_role: homeassistant
hassio_api: true
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
  - /dev/i2c-21
  - /dev/i2c-22
  - /dev/i2c-23
  - /dev/i2c-24
  - /dev/i2c-25
  - /dev/i2c-26
url: https://community.home-assistant.io/t/argon-one-active-cooling-addon/262598/
map:
  - homeassistant_config
  - ssl
  - addons
  - backup
  - share
  - media

options:
  fan_control_mode:
    name: "Fan Control Mode"
    description: "Choose the fan control mode for temperature regulation."
    selector:
      select:
        options:
          - linear
          - fluid
          - extended
          - custom
    default: linear

  create_fan_entity:
    name: "Create Fan Speed Entity"
    description: "Create a fan speed entity in Home Assistant for monitoring."
    selector:
      boolean: {}
    default: true

  log_temperature:
    name: "Log Temperature"
    description: "Log current temperature every specified interval."
    selector:
      boolean: {}
    default: true

  update_interval:
    name: "Update Interval"
    description: "Interval (in seconds) to update the temperature."
    selector:
      number:
        min: 1
        max: 3600
        step: 1
    default: 30

  min_temperature:
    name: "Minimum Temperature"
    description: "Set the minimum temperature threshold."
    selector:
      number:
        min: 0
        max: 255
        unit_of_measurement: "°C"
    default: 20

  max_temperature:
    name: "Maximum Temperature"
    description: "Set the maximum temperature threshold."
    selector:
      number:
        min: 0
        max: 255
        unit_of_measurement: "°C"
    default: 70

  fluid_sensitivity:
    name: "Fluid Sensitivity"
    description: "Set the sensitivity of the fluid mode."
    selector:
      number:
        min: 0
        max: 10
        step: 0.1
    default: 2.0

  extended_off_temp:
    name: "Extended Off Temperature"
    description: "Temperature at which the fan will be off in extended mode."
    selector:
      number:
        min: 0
        max: 255
        unit_of_measurement: "°C"
    default: 20

  extended_low_temp:
    name: "Extended Low Temperature"
    description: "Temperature for low fan speed in extended mode."
    selector:
      number:
        min: 0
        max: 255
        unit_of_measurement: "°C"
    default: 30

  extended_med_temp:
    name: "Extended Medium Temperature"
    description: "Temperature for medium fan speed in extended mode."
    selector:
      number:
        min: 0
        max: 255
        unit_of_measurement: "°C"
    default: 40

  extended_high_temp:
    name: "Extended High Temperature"
    description: "Temperature for high fan speed in extended mode."
    selector:
      number:
        min: 0
        max: 255
        unit_of_measurement: "°C"
    default: 50

  extended_boost_temp:
    name: "Extended Boost Temperature"
    description: "Temperature for boost fan speed in extended mode."
    selector:
      number:
        min: 0
        max: 255
        unit_of_measurement: "°C"
    default: 60

  quiet_profile:
    name: "Quiet Profile"
    description: "Enable a quieter profile by limiting the fan speed."
    selector:
      boolean: {}
    default: true

schema:
  fan_control_mode: str
  create_fan_entity: bool
  log_temperature: bool
  update_interval: int(1,3600)
  min_temperature: int(0,255)
  max_temperature: int(0,255)
  fluid_sensitivity: float(0,10)
  extended_off_temp: float(0,255)
  extended_low_temp: float(0,255)
  extended_med_temp: float(0,255)
  extended_high_temp: float(0,255)
  extended_boost_temp: float(0,255)
  quiet_profile: bool

panel_icon: mdi:fan
panel_title: "ArgonOne V3 Master Cooling"
panel_admin: true

advanced: true
stage: stable
init: true
