version: 30a
slug: argon_one_v3_master_temp
name: ArgonOne V3 Master Cooling
description: "Master fan control for ArgonOne V3 case for ultimate temperature regulation."
arch:
  - armhf
  - armv7
  - aarch64
auth_api: true
homeassistant_api: true
hassio_role: homeassistant
hassio_api: true
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
  - /dev/i2c-21
  - /dev/i2c-22
  - /dev/i2c-23
  - /dev/i2c-24
  - /dev/i2c-25
  - /dev/i2c-26
url: https://community.home-assistant.io/t/argon-one-active-cooling-addon/262598/
map:
  - homeassistant_config
  - ssl
  - addons
  - backup
  - share
  - media
options:
  fan_control_mode: linear  # linear, fluid, extended
  Celsius_or_Fahrenheit: C  # C or F
  Create_a_Fan_Speed_entity_in_Home_Assistant: true
  Log_current_temperature_every_30_seconds: true
  Update_Interval: 30  # Interval for updating the temperature (in seconds)
  Minimum_Temperature: 20
  Maximum_Temperature: 70
  Fluid_Sensitivity: 2.0
  Extended_Off_Temperature: 20
  Extended_Low_Temperature: 30
  Extended_Medium_Temperature: 40
  Extended_High_Temperature: 50
  Extended_Boost_Temperature: 60
  Quiet_Profile: true
schema:
  fan_control_mode: str
  Celsius_or_Fahrenheit: list(C|F)
  Create_a_Fan_Speed_entity_in_Home_Assistant: bool
  Log_current_temperature_every_30_seconds: bool
  Update_Interval: int(1,3600)
  Minimum_Temperature: int(0,255)
  Maximum_Temperature: int(0,255)
  Fluid_Sensitivity: float(0,10)
  Extended_Off_Temperature: float(0,255)
  Extended_Low_Temperature: float(0,255)
  Extended_Medium_Temperature: float(0,255)
  Extended_High_Temperature: float(0,255)
  Extended_Boost_Temperature: float(0,255)
  Quiet_Profile: bool
