version: 30a
slug: argon_one_v3_master_temp
name: ArgonOne V3 Master Cooling
description: "Master fan control for ArgonOne V3 case for ultimate temperature regulation."
arch:
  - armhf
  - armv7
  - aarch64
auth_api: true
homeassistant_api: true
hassio_role: homeassistant
hassio_api: true
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-2
  - /dev/i2c-3
  - /dev/i2c-4
  - /dev/i2c-5
  - /dev/i2c-6
  - /dev/i2c-7
  - /dev/i2c-8
  - /dev/i2c-9
  - /dev/i2c-10
  - /dev/i2c-11
  - /dev/i2c-12
  - /dev/i2c-13
  - /dev/i2c-14
  - /dev/i2c-15
  - /dev/i2c-16
  - /dev/i2c-17
  - /dev/i2c-18
  - /dev/i2c-19
  - /dev/i2c-20
  - /dev/i2c-21
  - /dev/i2c-22
  - /dev/i2c-23
  - /dev/i2c-24
  - /dev/i2c-25
  - /dev/i2c-26
url: https://community.home-assistant.io/t/argon-one-active-cooling-addon/262598/
map:
  - homeassistant_config
  - ssl
  - addons
  - backup
  - share
  - media
options:
  fan_control_mode: linear  # linear, fluid, extended
  Celsius or Fahrenheit: C  # C or F
  Create a Fan Speed entity in Home Assistant: true
  Log current temperature every 30 seconds: true
  Update Interval: 30  # Interval for updating the temperature (in seconds)
  Minimum Temperature: 20
  Maximum Temperature: 70
  Fluid Sensitivity: 2.0
  Extended Off Temperature: 20
  Extended Low Temperature: 30
  Extended Medium Temperature: 40
  Extended High Temperature: 50
  Extended Boost Temperature: 60
  Quiet Profile: true
schema:
  fan_control_mode: str
  Celsius or Fahrenheit: list(C|F)
  Create a Fan Speed entity in Home Assistant: bool
  Log current temperature every 30 seconds: bool
  Update Interval: int(1,3600)
  Minimum Temperature: int(0,255)
  Maximum Temperature: int(0,255)
  Fluid Sensitivity: float(0,10)
  Extended Off Temperature: float(0,255)
  Extended Low Temperature: float(0,255)
  Extended Medium Temperature: float(0,255)
  Extended High Temperature: float(0,255)
  Extended Boost Temperature: float(0,255)
  Quiet Profile: bool
